/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KitchenCard: typeof import('./src/components/KitchenCard.vue')['default']
    MenuAppBar: typeof import('./src/components/MenuAppBar.vue')['default']
    MenuCard: typeof import('./src/components/MenuCard.vue')['default']
    MenuDialog: typeof import('./src/components/MenuDialog.vue')['default']
    MenuFooter: typeof import('./src/components/MenuFooter.vue')['default']
    MenuSidebar: typeof import('./src/components/MenuSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
