/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AdminAparelhos': RouteRecordInfo<'/AdminAparelhos', '/AdminAparelhos', Record<never, never>, Record<never, never>>,
    '/AdminLogin': RouteRecordInfo<'/AdminLogin', '/AdminLogin', Record<never, never>, Record<never, never>>,
    '/AdminMetricas': RouteRecordInfo<'/AdminMetricas', '/AdminMetricas', Record<never, never>, Record<never, never>>,
    '/AdminPratos': RouteRecordInfo<'/AdminPratos', '/AdminPratos', Record<never, never>, Record<never, never>>,
    '/Cardapio': RouteRecordInfo<'/Cardapio', '/Cardapio', Record<never, never>, Record<never, never>>,
    '/Comandas': RouteRecordInfo<'/Comandas', '/Comandas', Record<never, never>, Record<never, never>>,
  }
}
